services:
  - type: web
    name: garfield
    repo: https://github.com/naxordeve/whatsapp-bot.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_APP_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION_ID
        sync: false
        required: true
      - key: THEME
        sync: false
        required: true
        
